version: '3.8'

services:
  web:
    build: .
    container_name: todo-app-frontend
    volumes:
      - ./:/react-docker:delegated
      - /node_modules
    ports:
      - 3000:3000
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: npm run start-watch